"use client";

import { motion } from "framer-motion";
import GlassCard from "@/components/ui/GlassCard";
import { Radio, Zap, Target, ArrowRight, Activity, AlertTriangle } from "lucide-react";
import { useApp } from "@/context/AppContext";

const signals = [
  { 
    id: 1, pair: "BTC/USDT", type: "LONG", entry: "64,500 - 65,000", targets: ["66,500", "68,000", "72,000"],
    stopLoss: "62,500", confidence: 92, timeframe: "4H", status: "Active", time: "2 hours ago"
  },
  { 
    id: 2, pair: "ETH/USDT", type: "SHORT", entry: "3,550 - 3,600", targets: ["3,400", "3,250", "3,000"],
    stopLoss: "3,750", confidence: 85, timeframe: "1D", status: "Pending", time: "5 hours ago"
  },
  { 
    id: 3, pair: "SOL/USDT", type: "LONG", entry: "140 - 142", targets: ["155", "165", "180"],
    stopLoss: "132", confidence: 78, timeframe: "1H", status: "Active", time: "30 mins ago"
  },
  { 
    id: 4, pair: "LINK/USDT", type: "LONG", entry: "18.00 - 18.20", targets: ["19.50", "21.00", "24.00"],
    stopLoss: "17.10", confidence: 65, timeframe: "15m", status: "Completed", time: "1 day ago"
  },
];

export default function Signals() {
  const { addToast } = useApp();

  const handlePerformanceHistory = () => {
    addToast("Generating AI Signal historical performance logs...", "info");
  };

  const handleAutoTrade = (pair: string) => {
    addToast(`Auto-trading engine activated for ${pair}! Executing trade parameters...`, "success");
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="max-w-7xl mx-auto space-y-8"
    >
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-2 flex items-center gap-3">
            AI Trading Signals <span className="bg-brand text-white text-xs px-2 py-1 rounded font-bold uppercase tracking-wider box-glow">Pro Feature</span>
          </h1>
          <p className="text-muted-foreground">High-probability trade setups generated by our proprietary AI engine.</p>
        </div>
        <button onClick={handlePerformanceHistory} className="px-4 py-2 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-lg font-medium transition-colors flex items-center gap-2">
          <Activity className="w-4 h-4" />
          Performance History
        </button>
      </div>

      <div className="bg-brand/10 border border-brand/20 rounded-xl p-4 flex items-start gap-4 box-glow">
        <AlertTriangle className="w-6 h-6 text-brand shrink-0 mt-0.5" />
        <div>
          <h3 className="text-white font-bold mb-1">Disclaimer</h3>
          <p className="text-sm text-muted-foreground">
            Trading signals are algorithmic suggestions based on technical analysis and market momentum. They do not constitute financial advice. Always use strict risk management and never risk more than 1-2% of your account per trade.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {signals.map((signal) => (
          <GlassCard key={signal.id} className="relative overflow-hidden">
            {signal.status === 'Completed' && (
              <div className="absolute inset-0 bg-black/40 backdrop-blur-[2px] z-10 flex items-center justify-center">
                <div className="bg-green-500/20 text-green-500 border border-green-500/50 px-4 py-2 rounded-lg font-bold backdrop-blur-md transform rotate-[-10deg]">
                  TARGET 2 HIT (+45%)
                </div>
              </div>
            )}
            
            <div className="flex justify-between items-start mb-6">
              <div className="flex items-center gap-3">
                <div className={`w-12 h-12 rounded-full flex items-center justify-center font-bold text-white shadow-inner ${
                  signal.type === 'LONG' ? 'bg-gradient-to-tr from-green-600 to-green-400' : 'bg-gradient-to-tr from-red-600 to-red-400'
                }`}>
                  {signal.pair.split('/')[0][0]}
                </div>
                <div>
                  <div className="font-bold text-white text-lg">{signal.pair}</div>
                  <div className="text-xs text-muted-foreground flex items-center gap-1">
                    <Radio className="w-3 h-3" /> {signal.time}
                  </div>
                </div>
              </div>
              
              <div className="text-right">
                <div className={`text-lg font-black uppercase tracking-wider ${signal.type === 'LONG' ? 'text-green-500' : 'text-red-500'}`}>
                  {signal.type}
                </div>
                <div className="text-xs font-medium px-2 py-0.5 bg-white/5 rounded border border-white/10 mt-1 inline-block">
                  {signal.timeframe} Chart
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-6">
              <div className="bg-black/20 rounded-lg p-3 border border-white/5">
                <div className="text-xs text-muted-foreground mb-1">Entry Zone</div>
                <div className="font-bold text-white text-sm">{signal.entry}</div>
              </div>
              <div className="bg-red-500/10 rounded-lg p-3 border border-red-500/20">
                <div className="text-xs text-red-500 mb-1">Stop Loss</div>
                <div className="font-bold text-red-500 text-sm">{signal.stopLoss}</div>
              </div>
            </div>

            <div className="mb-6">
              <div className="flex items-center gap-2 mb-3">
                <Target className="w-4 h-4 text-brand" />
                <span className="text-sm font-bold text-white">Take Profit Targets</span>
              </div>
              <div className="flex justify-between gap-2">
                {signal.targets.map((target, i) => (
                  <div key={i} className="flex-1 bg-brand/10 border border-brand/20 rounded py-2 text-center text-brand font-medium text-sm">
                    TP{i+1}: {target}
                  </div>
                ))}
              </div>
            </div>

            <div className="flex items-center justify-between mt-auto pt-4 border-t border-white/10">
              <div className="flex items-center gap-2">
                <Zap className="w-4 h-4 text-yellow-500" />
                <span className="text-sm text-muted-foreground">AI Confidence:</span>
                <span className={`text-sm font-bold ${signal.confidence >= 80 ? 'text-green-500' : 'text-yellow-500'}`}>
                  {signal.confidence}%
                </span>
              </div>
              
              <button onClick={() => handleAutoTrade(signal.pair)} className="text-sm bg-white/10 hover:bg-white/20 text-white px-4 py-1.5 rounded transition-colors flex items-center gap-1">
                Auto-Trade <ArrowRight className="w-3 h-3" />
              </button>
            </div>
          </GlassCard>
        ))}
      </div>
    </motion.div>
  );
}
